### ISSUE TITLE
Fix intermittent spec failure

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#187]
```
  1) UsersController sudo should not update IP or last_request_at
     Failure/Error: expect(users(:arthur).last_request_at.to_s).to eq(1.day.ago.to_s) # shouldn't have changed from yml
       expected: "2018-08-20 03:19:52 UTC"
            got: "2018-08-20 03:19:51 UTC"
       (compared using ==)
     # ./spec/controllers/users_controller_spec.rb:225:in `block (3 levels) in <top (required)>'
```

**Comment by innatewonderer** [comment]
Ha, started googing to see if I can find an elegant solution to deal with failing specs that deal with time.
First article:

<img width="1280" alt="fullscreen_8_22_18__7_32_pm" src="https://user-images.githubusercontent.com/2320322/44561125-071e8480-a721-11e8-9f02-ffc081fcacec.png">

**Comment by sudara** [comment]
Looks like this is still open:

https://travis-ci.com/sudara/alonetone/builds/83677444?utm_source=slack&utm_medium=notification

Prob just need to increase the time frame...

```
  1) UsersController sudo should not update IP or last_request_at
     Failure/Error: expect(users(:arthur).last_request_at.utc).to be_within(1.second).of 1.day.ago # shouldn't have changed from yml
       expected 2018-09-03 00:02:53.000000000 +0000 to be within 1 of 2018-09-03 00:02:54 UTC
     # ./spec/controllers/users_controller_spec.rb:225:in `block (3 levels) in <top (required)>'
```
