### ISSUE TITLE
Localhost 500s don't show always show a backtrace

### ISSUE THREAD

**Issue by sudara** [sudara/alonetone#855]
Localhost 500s should show backtraces in the browser and logs. Sometimes we are seeing production-like behavior with `pages#error` rendering.

```
Processing by PagesController#error as HTML
  Parameters: {"user_id"=>"marieh", "id"=>"new-playlist"}
  User Load (0.3ms)  SELECT `users`.* FROM `users` WHERE `users`.`deleted_at` IS NULL AND `users`.`id` = 4 LIMIT 1
  ↳ lib/authlogic_helpers.rb:5:in `current_user_session'
  Rendering layouts/about.html.erb
  Rendering pages/error.html.erb within layouts/about
  Rendered pages/error.html.erb within layouts/about (Duration: 0.7ms | Allocations: 255)
  Rendered pages/_navigation.html.erb (Duration: 3.0ms | Allocations: 3583)
  Rendering layouts/white_theme.html.erb
  Rendered shared/_headway.html.erb (Duration: 0.2ms | Allocations: 104)
  CACHE Playlist Load (0.0ms)  SELECT `playlists`.* FROM `playlists` WHERE `playlists`.`deleted_at` IS NULL AND `playlists`.`user_id` = 4 AND `playlists`.`is_favorite` = TRUE ORDER BY playlists.position LIMIT 1
  ↳ app/models/user.rb:181:in `favorites'
   (0.3ms)  SELECT `tracks`.`asset_id` FROM `tracks` WHERE `tracks`.`deleted_at` IS NULL AND `tracks`.`playlist_id` = 7
  ↳ app/models/user/settings.rb:18:in `favorite_asset_ids'
  Rendered shared/_javascript_payload.html.erb (Duration: 3.3ms | Allocations: 2138)
  Rendered shared/_analytics.html.erb (Duration: 0.3ms | Allocations: 146)
  Rendered shared/_flash.html.erb (Duration: 0.9ms | Allocations: 107)
  Rendered shared/_search.html.erb (Duration: 0.8ms | Allocations: 433)
  ActiveStorage::Attachment Load (0.4ms)  SELECT `active_storage_attachments`.* FROM `active_storage_attachments` WHERE `active_storage_attachments`.`record_id` = 4 AND `active_storage_attachments`.`record_type` = 'User' AND `active_storage_attachments`.`name` = 'avatar_image' LIMIT 1
  ↳ app/models/user.rb:254:in `avatar_image_location'
  ActiveStorage::Blob Load (0.2ms)  SELECT `active_storage_blobs`.* FROM `active_storage_blobs` WHERE `active_storage_blobs`.`id` = 2 LIMIT 1
  ↳ app/models/image_variant.rb:36:in `to_active_storage_variant'
  Disk Storage (0.1ms) Checked if file exists at key: variants/0joli500mu3pp698h5hdqc4t8gap/a0185d48b55de4674c54fb523cd6f35eb30aa089b7bdd27dc954c302b27b3f85 (yes)
  Disk Storage (0.3ms) Generated URL for file at key: variants/0joli500mu3pp698h5hdqc4t8gap/a0185d48b55de4674c54fb523cd6f35eb30aa089b7bdd27dc954c302b27b3f85 (http://localhost:3000/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSnJkbUZ5YVdGdWRITXZNR3B2YkdrMU1EQnRkVE53Y0RZNU9HZzFhR1J4WXpSME9HZGhjQzloTURFNE5XUTBPR0kxTldSbE5EWTNOR00xTkdaaU5USXpZMlEyWmpNMVpXSXpNR0ZoTURnNVlqZGlaR1F5TjJSak9UVTBZek13TW1JeU4ySXpaamcxQmpvR1JWUTZFR1JwYzNCdmMybDBhVzl1U1NJOWFXNXNhVzVsT3lCbWFXeGxibUZ0WlQwaWJXRnlhV1V1YW5Cbklqc2dabWxzWlc1aGJXVXFQVlZVUmkwNEp5ZHRZWEpwWlM1cWNHY0dPd1pVT2hGamIyNTBaVzUwWDNSNWNHVkpJZzlwYldGblpTOXFjR1ZuQmpzR1ZBPT0iLCJleHAiOiIyMDE5LTEwLTE4VDE0OjI4OjQ1LjYyN1oiLCJwdXIiOiJibG9iX2tleSJ9fQ==--fee6a73e59dc2c2f57dfef274660781742b6de3e/marie.jpg?content_type=image%2Fjpeg&disposition=inline%3B+filename%3D%22marie.jpg%22%3B+filename%2A%3DUTF-8%27%27marie.jpg)
  Disk Storage (0.0ms) Checked if file exists at key: variants/0joli500mu3pp698h5hdqc4t8gap/a0185d48b55de4674c54fb523cd6f35eb30aa089b7bdd27dc954c302b27b3f85 (yes)
  Disk Storage (0.3ms) Generated URL for file at key: variants/0joli500mu3pp698h5hdqc4t8gap/a0185d48b55de4674c54fb523cd6f35eb30aa089b7bdd27dc954c302b27b3f85 (http://localhost:3000/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDRG9JYTJWNVNTSnJkbUZ5YVdGdWRITXZNR3B2YkdrMU1EQnRkVE53Y0RZNU9HZzFhR1J4WXpSME9HZGhjQzloTURFNE5XUTBPR0kxTldSbE5EWTNOR00xTkdaaU5USXpZMlEyWmpNMVpXSXpNR0ZoTURnNVlqZGlaR1F5TjJSak9UVTBZek13TW1JeU4ySXpaamcxQmpvR1JWUTZFR1JwYzNCdmMybDBhVzl1U1NJOWFXNXNhVzVsT3lCbWFXeGxibUZ0WlQwaWJXRnlhV1V1YW5Cbklqc2dabWxzWlc1aGJXVXFQVlZVUmkwNEp5ZHRZWEpwWlM1cWNHY0dPd1pVT2hGamIyNTBaVzUwWDNSNWNHVkpJZzlwYldGblpTOXFjR1ZuQmpzR1ZBPT0iLCJleHAiOiIyMDE5LTEwLTE4VDE0OjI4OjQ1LjYyN1oiLCJwdXIiOiJibG9iX2tleSJ9fQ==--fee6a73e59dc2c2f57dfef274660781742b6de3e/marie.jpg?content_type=image%2Fjpeg&disposition=inline%3B+filename%3D%22marie.jpg%22%3B+filename%2A%3DUTF-8%27%27marie.jpg)
  Rendered shared/_header.html.erb (Duration: 7.5ms | Allocations: 4898)
  Rendered shared/_search.html.erb (Duration: 0.3ms | Allocations: 225)
   (0.4ms)  SELECT COUNT(*) FROM `users` WHERE `users`.`deleted_at` IS NULL AND (last_request_at > '2019-10-18 14:08:45.630061')
  ↳ app/views/shared/_footer_white.html.erb:1
  Rendering app/assets/images/svg/icon_caret.svg
  Rendered app/assets/images/svg/icon_caret.svg (Duration: 0.1ms | Allocations: 4)
  SQL (0.9ms)  SELECT `thredded_topics`.`id` AS t0_r0, `thredded_topics`.`user_id` AS t0_r1, `thredded_topics`.`last_user_id` AS t0_r2, `thredded_topics`.`title` AS t0_r3, `thredded_topics`.`slug` AS t0_r4, `thredded_topics`.`messageboard_id` AS t0_r5, `thredded_topics`.`posts_count` AS t0_r6, `thredded_topics`.`sticky` AS t0_r7, `thredded_topics`.`locked` AS t0_r8, `thredded_topics`.`hash_id` AS t0_r9, `thredded_topics`.`moderation_state` AS t0_r10, `thredded_topics`.`last_post_at` AS t0_r11, `thredded_topics`.`created_at` AS t0_r12, `thredded_topics`.`updated_at` AS t0_r13, `users`.`id` AS t1_r0, `users`.`login` AS t1_r1, `users`.`email` AS t1_r2, `users`.`salt` AS t1_r3, `users`.`created_at` AS t1_r4, `users`.`updated_at` AS t1_r5, `users`.`admin` AS t1_r6, `users`.`last_login_at` AS t1_r7, `users`.`crypted_password` AS t1_r8, `users`.`assets_count` AS t1_r9, `users`.`display_name` AS t1_r10, `users`.`playlists_count` AS t1_r11, `users`.`listens_count` AS t1_r12, `users`.`itunes` AS t1_r13, `users`.`comments_count` AS t1_r14, `users`.`last_login_ip` AS t1_r15, `users`.`settings` AS t1_r16, `users`.`posts_count` AS t1_r17, `users`.`moderator` AS t1_r18, `users`.`followers_count` AS t1_r19, `users`.`login_count` AS t1_r20, `users`.`current_login_at` AS t1_r21, `users`.`current_login_ip` AS t1_r22, `users`.`persistence_token` AS t1_r23, `users`.`perishable_token` AS t1_r24, `users`.`last_request_at` AS t1_r25, `users`.`bandwidth_used` AS t1_r26, `users`.`greenfield_enabled` AS t1_r27, `users`.`use_old_theme` AS t1_r28, `users`.`is_spam` AS t1_r29, `users`.`deleted_at` AS t1_r30 FROM `thredded_topics` INNER JOIN `users` ON `users`.`deleted_at` IS NULL AND `users`.`id` = `thredded_topics`.`last_user_id` WHERE (`thredded_topics`.`moderation_state` = 1 OR `thredded_topics`.`user_id` = 4) ORDER BY `thredded_topics`.`last_post_at` DESC, `thredded_topics`.`id` DESC LIMIT 4
  ↳ app/views/shared/_footer_white.html.erb:22
  Rendering app/assets/images/svg/icon_radio.svg
  Rendered app/assets/images/svg/icon_radio.svg (Duration: 0.1ms | Allocations: 4)
  Rendered shared/_footer_white.html.erb (Duration: 7.8ms | Allocations: 3605)
  Rendering app/assets/images/svg/animation_play.svg
  Rendered app/assets/images/svg/animation_play.svg (Duration: 0.2ms | Allocations: 4)
  Rendered layouts/white_theme.html.erb (Duration: 77.1ms | Allocations: 25275)
  Rendered layouts/about.html.erb (Duration: 82.4ms | Allocations: 29707)
Completed 500 Internal Server Error in 86ms (Views: 81.6ms | ActiveRecord: 2.5ms | Allocations: 31830)
```

**Comment by sudara** [comment]
Still seeing this on pages_controller

``` 
Processing by PagesController#about as HTML
  User Load (0.3ms)  SELECT `users`.* FROM `users` WHERE `users`.`deleted_at` IS NULL AND `users`.`id` = 2 LIMIT 1
  ↳ lib/authlogic_helpers.rb:5:in `current_user_session'
   (0.1ms)  BEGIN
  ↳ lib/authlogic_helpers.rb:5:in `current_user_session'
  User Update (0.4ms)  UPDATE `users` SET `users`.`updated_at` = '2019-10-22 15:28:13', `users`.`last_request_at` = '2019-10-22 15:28:13' WHERE `users`.`id` = 2
  ↳ lib/authlogic_helpers.rb:5:in `current_user_session'
   (86.3ms)  COMMIT
  ↳ lib/authlogic_helpers.rb:5:in `current_user_session'
  Rendering layouts/about.html.erb
  Rendering pages/about.html.md within layouts/about
  Rendered pages/about.html.md within layouts/about (Duration: 11.3ms | Allocations: 1030)
  Rendered layouts/about.html.erb (Duration: 11.6ms | Allocations: 1135)
Completed 500 Internal Server Error in 152ms (ActiveRecord: 103.6ms | Allocations: 27746)
```

**Comment by sudara** [comment]
Going to close this, I've only see it happening when working on ERB rendering.
